spring:
  application:
    name: mybatis_blog-website
  datasource:
    url: jdbc:sqlite:file:./data/testdb
    driver-class-name: org.sqlite.JDBC
# 만약 데이터를 제대로 넣는 것 같은데
# springboot를 껐다 킬 경우 데이터가 모두 사라지는 경우
# 아래와 같이 mode always 로 되어 있어서 매번
# posts 테이블의 데이터를 삭제하고 깨끗하게 추가하고 있기 때문
# 매번 SQL 문을 초기화 하고 있는 상태
  sql:
    init:
      mode: never # 이 문장이 존재하면
      #SQL 다시 실행하지 않는 배포용 프로젝트가 된다.
#      mode: always # 이 문장이 존재하면 resources 내에 있는 sql
      # 을 읽어 자동으로 table 생성~ data 추가 수정 삭제 기재되어 있는
      # sql 코드를 자동으로 실행한다.

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.project.mybatis_blogwebsite: debug
    org.mybatis: debug
    org.springframework.jdbc: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} %msg%n"
  file:
    name: logs/app.log