spring:
  application:
    name: mybatis_blog-website
  datasource:
    url: jdbc:sqlite:file:./data/testdb
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.project.mybatis_blogwebsite: debug
    org.mybatis: debug
    org.springframework.jdbc: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} %msg%n"
  file:
    name: logs/app.log
